### ISSUE TITLE
date time is not defined

### ISSUE THREAD

**Issue by haris2887** [giuliolibrando/photoprism2immich#5]
After the lasted code fix, 
I am, getting the error:

`Scanning directory: /Orignals
Skipping unsupported file type: /Orignals/.DS_Store
Uploading file: /Orignals/2013/08/20130809_122538_CEA4BDD4.jpg
Traceback (most recent call last):
  File "/usr/local/bin/photoprism2immich", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/photoprism2immich/photoprism2immich.py", line 111, in main
    upload_files_from_path(args.originals, args.apikey, args.baseapiurl, args.log)
  File "/usr/local/lib/python3.10/site-packages/photoprism2immich/photoprism2immich.py", line 71, in upload_files_from_path
    upload(file_path, api_key, base_url, log_file)
  File "/usr/local/lib/python3.10/site-packages/photoprism2immich/photoprism2immich.py", line 20, in upload
    'fileCreatedAt': datetime.fromtimestamp(stats.st_mtime),
NameError: name 'datetime' is not defined`

**Comment by haris2887** [comment]
I have just pulled and build the latest changes you uploaded a few hours ago.
